[workspace]
members = [
    "crates/provider-claude",
    "crates/provider-codex",
    "crates/provider-sdk",
    "crates/vault-io",
    "src-tauri",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
